# Generated by Django 3.2.9 on 2021-12-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Header Image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Project Image'),
        ),
    ]
