# Generated by Django 3.2.9 on 2021-12-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211203_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feadback',
            name='feedback',
            field=models.CharField(max_length=100, verbose_name='Feedback'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
