# Generated by Django 3.2.9 on 2021-12-05 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211205_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feadback',
            old_name='messgae',
            new_name='message',
        ),
    ]
